# Generated by Django 3.2.5 on 2021-09-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeProjeto',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False)),
                ('ap_nome', models.CharField(max_length=50)),
                ('ap_descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('ap_ativa', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atividade_projeto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cg_id', models.AutoField(primary_key=True, serialize=False)),
                ('cg_nome', models.CharField(max_length=30)),
                ('cg_descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('cg_ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CheckpointProjeto',
            fields=[
                ('ccp_id', models.AutoField(primary_key=True, serialize=False)),
                ('ccp_data', models.DateField()),
                ('ccp_ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'checkpoint_projeto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('cl_id', models.AutoField(primary_key=True, serialize=False)),
                ('cl_nome', models.CharField(max_length=200)),
                ('cl_matricula', models.CharField(max_length=7, unique=True)),
                ('cl_data_contratacao', models.DateField()),
                ('cl_ativo', models.BooleanField()),
                ('cl_data_desligamento', models.DateTimeField(blank=True, null=True)),
                ('cl_tipo_contrato', models.CharField(max_length=50)),
                ('cl_tempo_escala', models.CharField(max_length=10)),
                ('cl_tempo_contrato', models.IntegerField(blank=True, null=True)),
                ('cl_ies', models.CharField(blank=True, max_length=30, null=True)),
                ('cl_orientador', models.CharField(blank=True, max_length=100, null=True)),
                ('cl_data_cadastro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'colaborador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColaboradorProjeto',
            fields=[
                ('cp_id', models.AutoField(primary_key=True, serialize=False)),
                ('cp_ponto_focal', models.BooleanField()),
            ],
            options={
                'db_table': 'colaborador_projeto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('cv_id', models.AutoField(primary_key=True, serialize=False)),
                ('cv_geo_id', models.IntegerField(blank=True, null=True)),
                ('cv_nome', models.CharField(max_length=30)),
                ('cv_descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('cv_data_inicio', models.DateTimeField()),
                ('cv_data_termino', models.DateTimeField()),
                ('cv_data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('cv_ativo', models.BooleanField(blank=True, null=True)),
                ('cv_data_desativacao', models.DateTimeField(blank=True, null=True)),
                ('cv_recurso', models.TextField()),
            ],
            options={
                'db_table': 'convenio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DicionarioErro',
            fields=[
                ('de_erro', models.AutoField(primary_key=True, serialize=False)),
                ('de_codigo', models.IntegerField()),
                ('de_mensagem', models.CharField(max_length=200)),
                ('de_percente_a', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dicionario_erro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DicionarioSucesso',
            fields=[
                ('ds_id', models.AutoField(primary_key=True, serialize=False)),
                ('ds_codigo', models.IntegerField()),
                ('ds_mensagem', models.CharField(max_length=200)),
                ('ds_pertence_a', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dicionario_sucesso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('eq_id', models.AutoField(primary_key=True, serialize=False)),
                ('eq_nome', models.CharField(max_length=50)),
                ('eq_descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('eq_patrimonio', models.CharField(blank=True, max_length=10, null=True)),
                ('eq_data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('eq_ativo', models.BooleanField(blank=True, null=True)),
                ('eq_data_desativacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipamentoProjeto',
            fields=[
                ('ep_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'equipamento_projeto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GastoConvenio',
            fields=[
                ('gc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gc_valor_gasto', models.TextField()),
                ('gc_valor_anterior', models.TextField()),
                ('gc_valor_atual', models.TextField()),
                ('gc_descricao', models.CharField(max_length=1000)),
                ('gc_data_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gasto_convenio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GastoProjeto',
            fields=[
                ('gp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gp_valor_gasto', models.TextField()),
                ('gp_valor_anterior', models.TextField()),
                ('gp_valor_atual', models.TextField()),
                ('gp_descricao', models.CharField(max_length=1000)),
                ('gp_data_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gasto_projeto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidenciasColaborador',
            fields=[
                ('ic_id', models.AutoField(primary_key=True, serialize=False)),
                ('ic_gravidade', models.CharField(max_length=2)),
                ('ic_observacao', models.CharField(max_length=1000)),
                ('ic_data', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incidencias_colaborador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('pj_id', models.AutoField(primary_key=True, serialize=False)),
                ('pj_geo_id', models.IntegerField()),
                ('pj_nome', models.CharField(max_length=100)),
                ('pj_descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('pj_recurso_financeiro', models.TextField()),
                ('pj_data_inicio', models.DateField()),
                ('pj_data_fim', models.DateField()),
                ('pj_data_cadastro', models.DateTimeField(blank=True, null=True)),
                ('pj_projeto', models.BooleanField(blank=True, null=True)),
                ('pj_data_desativacao', models.DateTimeField(blank=True, null=True)),
                ('pj_observacoes', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'projeto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('te_id', models.AutoField(primary_key=True, serialize=False)),
                ('te_descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('te_ativo', models.BooleanField()),
            ],
            options={
                'db_table': 'tipo_equipamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssociacaoEntreConvenios',
            fields=[
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='geral.convenio')),
                ('cv_data_associado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'associacao_entre_convenios',
                'managed': False,
            },
        ),
    ]
